server.port=0

application-title=Ticket Service

spring.application.name=ticket-service

spring.kafka.producer.bootstrap-servers=omnisupport-kafka:9093
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.topic.name=notificationTopic

spring.config.import=configserver:http://localhost:8888/